FORMAT: 1A

# DINA Taxonomy API (example)

Testing API-Blueprint for taxonomy API.

Data structures are described as MSON, see https://github.com/apiaryio/mson 

# Data Structures

## validationResult

+ nameStatus: notFound (enum, required) - Whether the give taxon is valid. 
    + Default: notFound
    + Members
        + notFound
        + notFccepted
        + accepted

## resourceObject

+ id: 1 (string) - The taxon id. Can this be modularized with MSON, while keeping the 'id'-key?
+ type: taxon (string)
+ attributes (taxonResult)

## taxonResult

+ taxonId: 1 (string, required)
+ rank: species (string, required)
+ taxonName (taxonName, required) - SEE BELOW
+ vernacularNames (array[vernacularName]) - SEE BELOW
+ synonyms (array[simpleTaxon]) - SEE BELOW
+ parent (simpleTaxon)
+ ancestors (array[ancestorTaxon]) - SEE BELOW
+ siblings (array[simpleTaxon])
+ children (array[simpleTaxon])
+ taxonomicSortOrder: 1 (number) - Positive integer representing the taxonomic sort order (ascending)
+ classificationId: c1 (string) - Identifier for the classification or checklist
+ accepted: true (boolean) - Indicated whether this is a taxonomically accepted name
+ taxonConceptRelation (taxonConceptRelation) - SEE BELOW
+ originalPublication (publication) -  SEE BELOW / Or should this be under taxonName?
+ conceptPublication (publication)
+ notes: Blackbird is the national bird of Sweden (string)

## simpleTaxon

+ taxonId (string, required) - Unique id for the taxon

## ancestorTaxon

+ taxonId (string)
+ taxonRank (string)
+ scientificName (string)

## taxonName

+ nameId: 1 (string, required)
+ scientificName: Turdus merula (string, required)
+ cursiveName: true (boolean)
+ author: Linné (string)
+ year: 1758 (string)
+ scientificNameConcatenated: Turdus merula L. 1758 (string)
+ basionym: Turdus merula (string)

## vernacularName 

+ lang: sv (string)
+ name: koltrast (string)

## taxonConceptRelation

+ isSameAs (simpleTaxon)
+ isPartOf (simpleTaxon)
+ hasParts (array[simpleTaxon])

## publication

+ publicationId: p1 (string, required) - Unique id for the publication
+ reference: Linné Systema Naturae 1758 (string) - Publication reference string

## jsonapi

+ version: 1.0 (string)

## meta

+ apiVersion: v0_2 (string)

# Group Taxon

Resource group related to taxa.



## Taxon validation [/v1/validation?filter%5BscientificName%5D={scientificName}]

Resource for validating taxa.

+ Parameters
    + scientificName: Turdus merula (string, required) - Scientific name to be validated

### Validate a taxon [GET]

Action for validating a single taxon.

+ Response 200 (application/json)
    + Attributes
        + jsonapi (jsonapi)
        + meta (meta)
        + data (validationResult)


## Single taxon [/v1/taxon?filter%5BtaxonId%5D={taxonId}]

Resource for managing (CRUD) a single taxon.

+ Parameters
    + taxonId: 1 (string, required) - Identifier for the taxon

### Show a taxon [GET]

Action for showing data / metadata about one taxon.

+ Response 200 (application/json)
    + Attributes
        + jsonapi (jsonapi)
        + meta (meta)
        + data (resourceObject)



## Taxon search [/v1/taxon?filter%5BscientificName%5D={scientificName}&filter%5Bauthor%5D={author}]

Example resource for validating scientific name and author. Returns full data on all matching taxa.

+ Parameters
    + scientificName: Turdus (string) - Scientific name to search
    + author: Turdus (string) - Author name

### Search a taxon [GET]

Action for a partial search for taxa.

+ Response 200 (application/json)
    + Attributes
        + jsonapi (jsonapi)
        + meta (meta)
            + results: 10 (number) - Number of results
        + data (array[resourceObject])