FORMAT: 1A

# DINA Taxonomy API (example)

Testing API-Blueprint for taxonomy API.

# Data Structures

## Taxon

+ taxonId (string, required) - Unique id for the taxon
+ taxonName (object) - Names and name metadata for the taxon

## Publication

+ publicationId (string, required) - Unique id for the publication
+ reference (string) - Publication reference string

# Group Taxon

Resource group related to taxa.

## Taxon Displaying Collection [/taxon/id/{taxon_id}]

Resource for one taxon.

### Show a taxon [GET]

Action for showing data / metadata about one taxon.

+ Response 200 (application/json)

        {
        "taxonId": "string",
        "notes": "string",
        "rank": "string",
        "taxonName": {
            "nameId": "string",
            "scientificName": "string",
            "cursiveName": boolean,
            "scientificNameAuthor": "string",
            "scientificNameYear": "string",
            "scientificNameConcatenated": "string",
            "basionym": "string",
            "vernacularNames": [
                {
                    "lang": "string",
                    "name": "string",
                }
            ]
        },
        "synonyms": [
            {
                "taxonId": "string",
            }
        ],
        "parent": 
            {
                "taxonId": "string",
            },
        "ancestors": [
            {
                "taxonId": "string",
                "taxonRank": "string",
                "scientificName": "string"
            }
        ],
        "siblings": [
            {
                "taxonId": "string",
            }
        ],
        "children": [
            {
                "taxonId": "string",
            }
        ],
        "taxonomicSortOrder": 0,
        "classification": "string",
        "accepted": boolean,
        "conceptRelations":
            {
                "isSameAs": 
                    {
                        "taxonId": "string"
                    }
                "isPartOf":
                    {
                        "taxonId": "string"
                    }
                "hasParts": [
                    {
                        "taxonId": "string"
                    }
                ]
            },
        "originalPublication": {
            "publicationId": "string",
            "reference": "string"
        },
        "conceptPublication": {
            "publicationId": "string",
            "reference": "string"
        }

## Taxon Search Collection [/taxon/search]

Resource for searching taxa.

### Search a taxon [GET]

Action for a partial search for taxa.

TODO:

- How to add search parameters

+ Response 200 (application/json)

        {
            "todo": "string",
        }