
version: '3.1'


services:

    web:
#        image: php:7-apache-buster

        # https://github.com/thecodingmachine/docker-images-php
        image: thecodingmachine/php:7.2-v2-apache

        container_name: devenv-web
#        env_file:
#            - .env
        environment:
#            PHP_EXTENSION_MONGODB: 1
#            PHP_EXTENSION_XDEBUG: 1
        ports:
            - 80:80
        volumes:
            - ./www:/var/www
#            - ./env:/var/env
