
version: '2'

services:

    backend:
        image: richarvey/nginx-php-fpm:1.3.5
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 80:80
        volumes:
            - ./html:/var/www/html
            - ./data:/var/www/data
            - ./errors:/var/www/errors
